import csv
import os
import json
import smtplib
import argparse
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Base directory setup
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Loading from project root if possible
load_dotenv(os.path.join(BASE_DIR, "..", ".env"))

DARAZ_FILE = os.path.join(BASE_DIR, "daraz_electronics.json")
PRICEOYE_FILE = os.path.join(BASE_DIR, "priceoye_electronics.json")

def load_deals():
    deals = []
    
    # Load Daraz
    if os.path.exists(DARAZ_FILE):
        try:
            with open(DARAZ_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for item in data:
                    deals.append({
                        "Brand Name": item.get('name', 'N/A'),
                        "Category": item.get('category', 'Electronics'),
                        "Discount": f"{item.get('discount_percentage', 0)}%",
                        "Source": "Daraz"
                    })
        except Exception as e:
            print(f"Error loading Daraz data: {e}")

    # Load PriceOye
    if os.path.exists(PRICEOYE_FILE):
        try:
            with open(PRICEOYE_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for item in data:
                    deals.append({
                        "Brand Name": item.get('name', 'N/A'),
                        "Category": item.get('category', 'Mobile'),
                        "Discount": f"{item.get('discount_percentage', 0)}%",
                        "Source": "PriceOye"
                    })
        except Exception as e:
            print(f"Error loading PriceOye data: {e}")
    
    # Sort by discount (simple string parse for sorting)
    try:
        deals.sort(key=lambda x: int(x['Discount'].replace('%','')), reverse=True)
    except:
        pass
        
    return deals[:10]

def send_email(to_email=None, is_confirmation=False):
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    default_to = os.getenv("ALERT_EMAIL_TO")

    target_email = to_email if to_email else default_to

    if not all([smtp_host, smtp_port, smtp_user, smtp_pass, target_email]):
        print(f"Error: Missing SMTP configuration in .env for {target_email}")
        return

    if is_confirmation:
        subject = "Welcome to Retail Monitor Pakistan Alerts!"
        html_content = f"""
        <html>
        <body style="font-family: sans-serif; color: #333;">
            <h2 style="color: #4f46e5;">Subscription Confirmed!</h2>
            <p>Hello,</p>
            <p>You have successfully subscribed to price alerts on <b>Retail Monitor Pakistan</b>. We will notify you whenever we find massive price drops in your selected categories.</p>
            <p>Happy Shopping!</p>
            <hr>
            <p style="font-size: 12px; color: #666;">This is an automated message from Retail Monitor.</p>
        </body>
        </html>
        """
    else:
        deals = load_deals()
        if not deals:
            print("No deals found to send.")
            return

        subject = "Daily Retail Sales Alert - Top Discounts Today"
        html_content = """
        <html>
        <body style="font-family: sans-serif; color: #333;">
            <h2 style="color: #0d9488;">Top 10 Tech Deals Today</h2>
            <table border="0" cellpadding="10" cellspacing="1" style="background-color: #e5e7eb; width: 100%;">
                <tr style="background-color: #1f2937; color: white;">
                    <th>Brand/Product</th>
                    <th>Category</th>
                    <th>Discount</th>
                    <th>Source</th>
                </tr>
        """
        
        for deal in deals:
            html_content += f"""
                <tr style="background-color: white;">
                    <td>{deal['Brand Name']}</td>
                    <td>{deal['Category']}</td>
                    <td style="color: #0d9488; font-weight: bold;">{deal['Discount']}</td>
                    <td>{deal['Source']}</td>
                </tr>
            """
        
        html_content += """
            </table>
            <p>Visit <a href="http://localhost:3000">Retail Monitor Pakistan</a> to see all live deals!</p>
            <hr>
            <p style="font-size: 12px; color: #666;">Generated by Agentic Retail Monitor</p>
        </body>
        </html>
        """

    msg = MIMEMultipart()
    msg['From'] = smtp_user
    msg['To'] = target_email
    msg['Subject'] = subject
    msg.attach(MIMEText(html_content, 'html'))

    try:
        print(f"Connecting to {smtp_host}:{smtp_port} for {target_email}...")
        server = smtplib.SMTP(smtp_host, int(smtp_port))
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.send_message(msg)
        server.quit()
        print(f"Email sent successfully to {target_email}")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Send email alerts.")
    parser.add_argument("--confirm", type=str, help="Email address to send confirmation to")
    args = parser.parse_args()

    if args.confirm:
        send_email(to_email=args.confirm, is_confirmation=True)
    else:
        send_email()
