import csv
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

# Load env
load_dotenv(dotenv_path=".env")

INPUT_FILE = ".tmp/live_retail_sales.csv"

def send_email():
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = os.getenv("SMTP_PORT")
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    to_email = os.getenv("ALERT_EMAIL_TO")

    if not all([smtp_host, smtp_port, smtp_user, smtp_pass, to_email]):
        print("Error: Missing SMTP configuration in .env")
        return

    # Read Data
    if not os.path.exists(INPUT_FILE):
        print(f"Error: Data file {INPUT_FILE} not found.")
        return

    top_deals = []
    with open(INPUT_FILE, mode='r', encoding='utf-8') as file:
        reader = csv.DictReader(file)
        # Assuming already sorted, but let's take top 10
        for row in reader:
            top_deals.append(row)
            if len(top_deals) >= 10:
                break
    
    # Format Email
    html_content = """
    <html>
    <body>
        <h2>Top 10 Retail Discounts in Pakistan</h2>
        <table border="1" cellpadding="5" cellspacing="0">
            <tr>
                <th>Brand</th>
                <th>Category</th>
                <th>Discount</th>
                <th>Source</th>
            </tr>
    """
    
    for deal in top_deals:
        html_content += f"""
            <tr>
                <td>{deal['Brand Name']}</td>
                <td>{deal['Category']}</td>
                <td>{deal['Discount Percentage']}</td>
                <td>{deal['Source']}</td>
            </tr>
        """
    
    html_content += """
        </table>
        <p><i>Generated by Agentic Retail Monitor</i></p>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = smtp_user
    msg['To'] = to_email
    msg['Subject'] = "Daily Retail Sales Alert - Top Discounts"
    msg.attach(MIMEText(html_content, 'html'))

    try:
        print(f"Connecting to {smtp_host}:{smtp_port}...")
        server = smtplib.SMTP(smtp_host, int(smtp_port))
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.send_message(msg)
        server.quit()
        print(f"Email sent successfully to {to_email}")
    except Exception as e:
        print(f"Failed to send email: {e}")

if __name__ == "__main__":
    send_email()
